### ISSUE TITLE
Issue with Markbot image size

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/columns-of-cards#1]
Hi,

On the assignment sheet it says the images are 100px but when I set the images to that width Markbot says it is expecting a different value under width. I don't know how to fix it, lol.

@thomasjbradley

Thanks for your help,
Jess

**Comment by thomasjbradley** [comment]
When we target `img` we’re targeting all possible images on the **whole website**—that should always be `100%`. 

But in this assignment we’re only designing a *small component*. We don’t want *every single image on the whole website* to be `100px` wide, only the images inside the cards. So we should do something like:

```css
.card img {
  width: 100px;
}
```
